server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://centerbeam.proxy.rlwy.net:26840/railway"
    username: "root"
    password: "VQcRxTwlSJgTAtpgMvUeUhsfrVzotsrN"
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signerKey: "QnH/fRs+uwNd2FoCyreG4O1xAd0v3/lEX6pTTRTQzHea9YtyVYrpuTOj31XK9Y2D"
